# Generated by Django 2.2.10 on 2021-06-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание опроса')),
                ('end_date', models.DateField(verbose_name='Дата завершения опроса')),
                ('start_date', models.DateField(verbose_name='Дата старта опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ID пользователя')),
                ('completion_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('O', 'Один вариант ответа'), ('M', 'Много вариантов ответа'), ('T', 'Текстовый ответ')], max_length=1, verbose_name='Тип вопроса')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('answer_text', models.TextField(verbose_name='Ответ пользователя')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='survey.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('O', 'Один вариант ответа'), ('M', 'Много вариантов ответа'), ('T', 'Текстовый ответ')], max_length=1, verbose_name='Тип вопроса')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='ID варианта ответа')),
                ('text', models.CharField(max_length=120, verbose_name='Текст варианат ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='survey.Question')),
            ],
        ),
    ]
